apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-heart-disease
  labels:
    app: mlops-heart-disease
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-heart-disease
  template:
    metadata:
      labels:
        app: mlops-heart-disease
    spec:
      containers:
      - name: mlops-api
        image: mlops-heart-disease:latest # Replace with registry tag for real deployment
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
